### ISSUE TITLE
support multi-arch docker images

### ISSUE THREAD

**Issue by BinaryMan32** [immanuelfodor/kube-karp#2]
I was hoping to try out this project on a cluster of raspberry pi 4s, but the [immanuelfodor/kube-karp](https://hub.docker.com/r/immanuelfodor/kube-karp) docker images are amd64 only.

Would you consider publishing arm64 docker images as well?

Here's a page that I referenced when working on multi-arch support for another project. It's for gitlab, but it shouldn't be too much work to convert the job to a drone pipeline.
https://www.auroria.io/docker-multi-architecture-builds-with-gitlab-runner/

**Comment by BinaryMan32** [comment]
Since the arm images are built with an emulator, the build can be rather slow. But since you're only running a single `apk` command, I'd expect this difference is minimal.

I was able to build the docker image on my raspberry pi 4 as of commit `65b8135`, but I haven't tested it yet to see if it works since I don't have a local docker registry in my cluster to store the image.

**Comment by BinaryMan32** [comment]
Oh, I see you're already working on this, I just found [blampe/kube-karp](https://hub.docker.com/r/blampe/kube-karp).

**Comment by immanuelfodor** [comment]
Thanks for opening this issue, and I'm happy to see that you find the project useful! 

I'll look into multi-architecture Docker builds with Drone to update the official image, the linked image is not mine :)

**Comment by BinaryMan32** [comment]
Ah, thanks for clarifying.

Still, later this weekend I may try the `1.0.0` image that @blampe published since that's easy to override. I'll let you know if it works for me.

I had considered using kube-vip, but decided I preferred kube-karp for 2 reasons:
* I already have metalLB configured, and I'm happy with it. I didn't want kube-vip to interfere with my `LoadBalancer` services.
* The instructions were great for a new cluster, but I wasn't sure how to use kube-vip to load balance k8s itself with an existing cluster.

**Comment by immanuelfodor** [comment]
I can relate to that, more or less this is why I created this project 😃 

It seems the recommended way is to define multiple pipelines with different archs then use the manifest plugin at the end: https://github.com/drone/drone/blob/master/.drone.yml

The docs is fairly short and doesn't speak about any requirements of the underlying host: https://docs.drone.io/pipeline/docker/syntax/platform/

I'll run some experiments with it tomorrow, I have been already thinking this day would come eventually 😃

**Comment by immanuelfodor** [comment]
After some trial and error, I managed to provide the multi-platform images with `buildx`, you can find them here: https://hub.docker.com/r/immanuelfodor/kube-karp/tags

Please test them if everything is fine, I don't have an ARM instance to try it.

Background: Using Drone's platform spec results in a forever-pending pipeline as I don't have Drone Agents running on ARM hosts that could grab the execution. I needed to add the `buildx` plugin manually as the official `docker:dind` image doesn't contain it, see https://github.com/docker-library/docker/issues/156#issuecomment-558410863 and https://github.com/docker/docker-ce-packaging/pull/415 . With some binary caching the build is fairly quick, about 30s.

**Comment by BinaryMan32** [comment]
Just wanted to let you know that I have kube-karp up and running in my cluster of 4 raspberry pi 4's now. It was easy to deploy, and I haven't noticed any issues since switching my `~/.kube/config` over to use the virtual IP.

Thanks for publishing the arm64 image so quickly.

**Comment by immanuelfodor** [comment]
Awesome, thanks for the follow-up! 🎉
