### ISSUE TITLE
Works with MetalLb?

### ISSUE THREAD

**Issue by kferrone** [immanuelfodor/kube-karp#3]
I found this for project for obvious reasons on MetalLb. So does this project work alongside MetalLb just fine? Or is this an alternative to?

**Comment by immanuelfodor** [comment]
As of now, MetalLB can't load balance the kube API server (https://github.com/metallb/metallb/issues/168), but Kube Karp can uniquely provide this feature, however, Kube Karp doesn't give you an internal `LoadBalancer` resource what MetalLB can. Explanation in the readme: https://github.com/immanuelfodor/kube-karp#how-does-kube-karp-compare-to-other-tools

I haven't tested alongside a MetalLB installation but theoretically it should work fine. To stay on the safe side, I'd probably choose a random server ID and use a virtual IP outside the range assigned to MetalLB. For example, if MetalLB can use 192.168.2.0/24 then set 192.168.3.X as the virtual IP for Kube Karp. There should be no problem then to access the kube api server and the exposed load balancers with different IPs which will never overlap.

**Comment by kferrone** [comment]
It works well with MetalLb!
