### ISSUE TITLE
publish on registry without draconian usage limits

### ISSUE THREAD

**Issue by ibotty** [immanuelfodor/kube-karp#4]
It would be great if you could publish the container image on another registry.  I do like quay.io, but any other registry is OK as well.

**Comment by immanuelfodor** [comment]
The poblem with Quay is that I'd need to pay for being not draconian 😃 https://quay.io/plans/

However, it seems I could utilize Github's own registry: 
- https://nikiforovall.github.io/docker/2020/09/19/publish-package-to-ghcr.html
- https://blog.codecentric.de/en/2021/03/github-container-registry/

Would ghcr.io be okay for you? Any limits here that I'm not aware of?

**Comment by immanuelfodor** [comment]
I might be able to implement it this weekend if you don't have any objection against ghcr, @ibotty

**Comment by ibotty** [comment]
No, that's fine as well AFAICT.

**Comment by ibotty** [comment]
> The poblem with Quay is that I'd need to pay for being not draconian smiley https://quay.io/plans/

Oh, I missed that comment.  No you do not have to pay.  See the FAQ below the plans.  Quote:

>  **Can I use Quay for free?**
> Yes! We offer unlimited storage and serving of public repositories. We strongly believe in the open source community and will do what we can to help!

That should be featured more prominently I'd say.

**Comment by immanuelfodor** [comment]
Yes, they seem to have a 0 USD tier for OSS but not so obvious from the pricing page, only available after starting the trial.

Done! :) 
- https://github.com/immanuelfodor/kube-karp/releases/tag/1.0.2
- https://quay.io/repository/immanuelfodor/kube-karp

**Comment by ibotty** [comment]
Thank you!
